spring:
  datasource:
    url: jdbc:mysql://localhost:3306/x_db
    username: root
    password: '12345'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.jdbc.time.zone: UTC
security:
  jwt:
    secret: ${SECRET}
    access: 1
    refresh: 24


